import { MyDatabase } from '@pulse/core-logic';
import { v4 as uuidv4 } from 'uuid';

const WORKSPACE_ID = '00000000-0000-0000-0000-000000000000';

const SAMPLE_PRODUCTS = [
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Coca Cola 330ml',
    barcode: '5449000000996',
    sku: 'COKE-330',
    cost_price: 0.80,
    sale_price: 1.50,
    stock_quantity: 100,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Sprite 330ml',
    barcode: '5449000017883',
    sku: 'SPRITE-330',
    cost_price: 0.75,
    sale_price: 1.50,
    stock_quantity: 85,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Fanta Orange 330ml',
    barcode: '5449000000446',
    sku: 'FANTA-330',
    cost_price: 0.75,
    sale_price: 1.50,
    stock_quantity: 78,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Water 500ml',
    barcode: '5449000214911',
    sku: 'WATER-500',
    cost_price: 0.30,
    sale_price: 0.80,
    stock_quantity: 200,
    min_stock_level: 50,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Coffee Cappuccino',
    barcode: '8410054906076',
    sku: 'COFFEE-CAP',
    cost_price: 1.20,
    sale_price: 2.50,
    stock_quantity: 45,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Chocolate Bar Milka',
    barcode: '7622300441265',
    sku: 'CHOC-MILKA',
    cost_price: 0.90,
    sale_price: 1.80,
    stock_quantity: 55,
    min_stock_level: 10,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Chips Lay\'s Classic',
    barcode: '5000328942926',
    sku: 'CHIPS-LAYS',
    cost_price: 0.70,
    sale_price: 1.40,
    stock_quantity: 120,
    min_stock_level: 30,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Energy Drink RedBull',
    barcode: '9002490100070',
    sku: 'ENERGY-RB',
    cost_price: 1.50,
    sale_price: 3.00,
    stock_quantity: 60,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Sandwich Ham & Cheese',
    barcode: '2000000000001',
    sku: 'SAND-HC',
    cost_price: 2.00,
    sale_price: 4.50,
    stock_quantity: 15,
    min_stock_level: 5,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Juice Orange 1L',
    barcode: '5449000131805',
    sku: 'JUICE-OR',
    cost_price: 1.80,
    sale_price: 3.50,
    stock_quantity: 35,
    min_stock_level: 10,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Gum Orbit',
    barcode: '8000500050002',
    sku: 'GUM-ORBIT',
    cost_price: 0.40,
    sale_price: 1.00,
    stock_quantity: 90,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Ice Cream Magnum',
    barcode: '8714100699492',
    sku: 'ICE-MAGNUM',
    cost_price: 1.50,
    sale_price: 3.20,
    stock_quantity: 40,
    min_stock_level: 10,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Bread White',
    barcode: '2100000000001',
    sku: 'BREAD-W',
    cost_price: 0.60,
    sale_price: 1.20,
    stock_quantity: 25,
    min_stock_level: 5,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Milk 1L',
    barcode: '5449000096517',
    sku: 'MILK-1L',
    cost_price: 1.20,
    sale_price: 2.30,
    stock_quantity: 50,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Beer Heineken 330ml',
    barcode: '8710103862048',
    sku: 'BEER-HEIN',
    cost_price: 1.00,
    sale_price: 2.20,
    stock_quantity: 72,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false, 
    age_restricted: true,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Biscuits Oreo',
    barcode: '7622300996628',
    sku: 'BISCUIT-OREO',
    cost_price: 1.00,
    sale_price: 2.00,
    stock_quantity: 65,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Shampoo Head & Shoulders',
    barcode: '8001841459684',
    sku: 'SHAMPOO-HS',
    cost_price: 3.50,
    sale_price: 6.80,
    stock_quantity: 25,
    min_stock_level: 10,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Soap Dove',
    barcode: '8717644249888',
    sku: 'SOAP-DOVE',
    cost_price: 1.20,
    sale_price: 2.50,
    stock_quantity: 0,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Toothpaste Colgate',
    barcode: '8714789732527',
    sku: 'TOOTHPASTE-COL',
    cost_price: 2.00,
    sale_price: 4.20,
    stock_quantity: 30,
    min_stock_level: 12,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Yogurt Danone',
    barcode: '3033710074426',
    sku: 'YOGURT-DAN',
    cost_price: 0.80,
    sale_price: 1.60,
    stock_quantity: 40,
    min_stock_level: 20,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Cheese Gouda',
    barcode: '8711200242207',
    sku: 'CHEESE-GOUDA',
    cost_price: 4.50,
    sale_price: 8.90,
    stock_quantity: 18,
    min_stock_level: 8,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Eggs (12 pack)',
    barcode: '2200000000001',
    sku: 'EGGS-12',
    cost_price: 2.50,
    sale_price: 4.80,
    stock_quantity: 55,
    min_stock_level: 15,
    is_active: true,
    updated_at: new Date().toISOString(),
    is_quick_key: false,
    age_restricted: false,
    _synced: false,
    _dirty: true,
  },
];

const SAMPLE_CUSTOMERS = [
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+359888123456',
    loyalty_points: 150,
    credit_balance: 50.00, // 50 BGN store credit for testing
    is_active: true,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+359888234567',
    loyalty_points: 320,
    credit_balance: 100.00, // 100 BGN store credit for testing
    is_active: true,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Ali Yılmaz',
    email: 'ali@example.com',
    phone: '+359888345678',
    loyalty_points: 85,
    credit_balance: 25.00, // 25 BGN store credit for testing
    is_active: true,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Ayşe Demir',
    email: 'ayse@example.com',
    phone: '+359888456789',
    loyalty_points: 420,
    credit_balance: 60.00, // 60 BGN store credit for testing
    is_active: true,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    name: 'Mehmet Kaya',
    email: 'mehmet@example.com',
    phone: '+359888567890',
    loyalty_points: 200,
    credit_balance: 0, // No credit for testing
    is_active: true,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
];

const SAMPLE_CASHIERS = [
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    username: 'admin',
    pin_code: '1234',
    full_name: 'Admin User',
    is_active: true,
    role: 'admin' as const,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
  {
    id: uuidv4(),
    workspace_id: WORKSPACE_ID,
    username: 'cashier1',
    pin_code: '5678',
    full_name: 'Mehmet Yılmaz',
    is_active: true,
    role: 'cashier' as const,
    created_at: new Date().toISOString(),
    _synced: false,
    _dirty: true,
  },
];

/**
 * Seed the local database with sample products and customers
 */
export async function seedDatabase(db: MyDatabase) {
  try {
    console.log('📦 Starting database seed...');

    // Clear old data first to prevent schema conflicts
    console.log('🗑️  Clearing existing products, customers, and cashiers...');
    await db.products.find().remove();
    await db.customers.find().remove();
    await db.cashiers.find().remove();

    // Map legacy fields if necessary, or assume types are correct now (we updated stock_quantity)
    // Seed products
    await db.products.bulkInsert(SAMPLE_PRODUCTS.map(p => ({
        ...p,
        stock_quantity: (p as any).stock_quantity ?? p.stock_quantity ?? 0
    })));
    console.log(`✅ Seeded ${SAMPLE_PRODUCTS.length} products`);
    
    // Seed customers
    await db.customers.bulkInsert(SAMPLE_CUSTOMERS);
    console.log(`✅ Seeded ${SAMPLE_CUSTOMERS.length} customers`);
    
    // Seed cashiers
    await db.cashiers.bulkInsert(SAMPLE_CASHIERS);
    console.log(`✅ Seeded ${SAMPLE_CASHIERS.length} cashiers`);
    
    return {
      success: true,
      productsAdded: SAMPLE_PRODUCTS.length,
      customersAdded: SAMPLE_CUSTOMERS.length,
      cashiersAdded: SAMPLE_CASHIERS.length,
    };
  } catch (error) {
    console.error('❌ Seed failed:', error);
    return {
      success: false,
      error: (error as Error).message,
    };
  }
}
